### LOGIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

> {%
    if (response.status >= 200 && response.status < 300) {
        client.global.set("token", response.body.accessToken);
        client.global.set("refreshToken", response.body.refreshToken);
    }
%}

### REFRESH
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}



### LOGIN
POST {{baseUrl}}/auth/logout
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}
