# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false

# NÃO rodar scripts automáticos
spring.sql.init.mode=never

# Desliga H2 console
spring.h2.console.enabled=false

# Performance
spring.main.lazy-initialization=true

# Segurança / limpeza
server.error.include-message=never

# Swagger
springdoc.api-docs.path=/api-fabricapins
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Porta (Render)
server.port=${PORT:8080}

