# Dados configuracao JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Configuracao do cliente web do banco h2
spring.sql.init.mode=never

# Configuracao do cliente web do banco postgresql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url= ${DB_URL}
spring.datasource.username= ${DB_USERNAME}
spring.datasource.password= ${DB_PASSWORD}

# Configuracao conexão com Neon
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# Configuracao Migracao do Banco de Dados
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Configuracao do servidor
server.error.include-message=always

# Configuracao do Swagger
springdoc.api-docs.path=/api-fabricapins
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Configuracao do Render
server.port=${PORT:8080}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Configuração de CORS
app.cors.allowed-origins = http://localhost:3000,http://localhost:5173,https://fabricapins-frontend.vercel.app

