create table tb_categoria (
                              ativa boolean not null,
                              id bigint generated by default as identity,
                              nome varchar(100) not null unique,
                              descricao varchar(255) not null,
                              primary key (id)
);

create table tb_cliente (
                            ativo boolean not null,
                            data_atualizacao timestamp(6) with time zone,
                            data_cadastro timestamp(6) with time zone not null,
                            id bigint generated by default as identity,
                            usuario_id bigint unique,
                            nome varchar(150) not null,
                            email varchar(255) not null unique,
                            numero_documento varchar(255) not null unique,
                            telefone varchar(255) not null,
                            tipo_cliente varchar(255) not null check (tipo_cliente in ('VAREJO','REVENDA')),
                            tipo_pessoa varchar(255) not null check (tipo_pessoa in ('FISICA','JURIDICA')),
                            primary key (id)
);

create table tb_cupom_desconto (
                                   ativo boolean not null,
                                   data_validade date,
                                   limite_usos integer not null,
                                   quantidade_minima_itens integer,
                                   valor_desconto numeric(15,2) not null,
                                   valor_minimo_pedido numeric(15,2),
                                   data_cadastro timestamp(6) with time zone not null,
                                   id bigint generated by default as identity,
                                   codigo varchar(30) not null unique,
                                   tipo_desconto varchar(255) not null check (tipo_desconto in ('PERCENTUAL','FIXO')),
                                   primary key (id)
);

create table tb_endereco (
                             endereco_principal boolean not null,
                             cep varchar(8) not null,
                             cliente_id bigint not null,
                             data_cadastro timestamp(6) with time zone not null,
                             id bigint generated by default as identity,
                             apelido varchar(255),
                             bairro varchar(255) not null,
                             cidade varchar(255) not null,
                             complemento varchar(255),
                             estado varchar(255) not null,
                             logradouro varchar(255) not null,
                             numero varchar(255) not null,
                             observacoes varchar(255),
                             ponto_referencia varchar(255),
                             tipo_endereco varchar(255) not null check (tipo_endereco in ('ENTREGA','COBRANCA')),
                             primary key (id)
);

create table tb_item_pedido (
                                custo_unitario_snapshot numeric(38,2),
                                preco_unitario numeric(15,2) not null,
                                quantidade integer not null check (quantidade>=1),
                                id bigint generated by default as identity,
                                pedido_id bigint,
                                produto_id bigint,
                                nome_produto_snapshot varchar(150) not null,
                                img_produto_snapshot varchar(255),
                                primary key (id)
);

create table tb_opcao_frete_pedido (
                                       prazo_dias integer,
                                       valor numeric(38,2),
                                       id bigint generated by default as identity,
                                       pedido_id bigint,
                                       empresa varchar(255),
                                       nome varchar(255),
                                       provider varchar(255),
                                       service_id varchar(255),
                                       primary key (id)
);

create table tb_pagamento (
                              parcelas_cartao integer,
                              valor_pago numeric(15,2) not null,
                              data_confirmacao timestamp(6) with time zone,
                              data_pagamento timestamp(6) with time zone,
                              id bigint generated by default as identity,
                              codigo_transacao varchar(255),
                              forma_pagamento varchar(255) not null check (forma_pagamento in ('PIX','CARTAO_CREDITO')),
                              gateway_pagamento varchar(255),
                              motivo_recusa varchar(255),
                              status_pagamento varchar(255) not null check (status_pagamento in ('PENDENTE','APROVADO','RECUSADO','ESTORNADO')),
                              primary key (id)
);

create table tb_parametro (
                              id bigint generated by default as identity,
                              chave varchar(255) not null unique check (chave in ('CEP_ORIGEM','FRETE_PROVIDER_PADRAO')),
                              valor varchar(255) not null,
                              primary key (id)
);

create table tb_pedido (
                           desconto numeric(15,2),
                           prazo_entrega_dias integer,
                           valor_desconto_final numeric(38,2),
                           valor_frete numeric(15,2),
                           valor_frete_final numeric(38,2),
                           valor_subtotal numeric(15,2) not null,
                           valor_total numeric(15,2) not null,
                           valor_total_final numeric(38,2),
                           cliente_id bigint,
                           data_aguardando_envio timestamp(6) with time zone,
                           data_atualizacao timestamp(6) with time zone,
                           data_calculo_frete timestamp(6) with time zone,
                           data_cancelamento timestamp(6) with time zone,
                           data_conclusao_pedido timestamp(6) with time zone,
                           data_criacao timestamp(6) with time zone not null,
                           data_entrega timestamp(6) with time zone,
                           data_envio timestamp(6) with time zone,
                           data_fim_producao timestamp(6) with time zone,
                           data_inicio_producao timestamp(6) with time zone,
                           data_pagamento_confirmado timestamp(6) with time zone,
                           data_separacao timestamp(6) with time zone,
                           id bigint generated by default as identity,
                           pagamento_id bigint unique,
                           codigo_pedido varchar(50) not null unique,
                           bairro varchar(255),
                           cep varchar(255),
                           cidade varchar(255),
                           complemento varchar(255),
                           documento_cliente varchar(255),
                           estado varchar(255),
                           frete_empresa varchar(255),
                           frete_service_id varchar(255),
                           logradouro varchar(255),
                           nome_cliente varchar(255),
                           nome_servico_frete varchar(255),
                           numero varchar(255),
                           observacao varchar(255),
                           origem_pedido varchar(255) not null check (origem_pedido in ('SITE','WHATSAPP','REDE_SOCIAL')),
                           ponto_referencia varchar(255),
                           status_pedido varchar(255) not null check (status_pedido in ('RASCUNHO','AGUARDANDO_PAGAMENTO','PAGAMENTO_CONFIRMADO','EM_PRODUCAO','EM_SEPARACAO','AGUARDANDO_ENVIO','ENVIADO','ENTREGUE','CANCELADO','REEMBOLSADO')),
                           telefone varchar(255),
                           tipo_cliente varchar(255) check (tipo_cliente in ('VAREJO','REVENDA')),
                           primary key (id)
);

create table tb_pedido_cupom (
                                 valor_desconto_aplicado numeric(15,2) not null,
                                 cupom_id bigint,
                                 data_aplicacao timestamp(6) with time zone,
                                 id bigint generated by default as identity,
                                 pedido_id bigint,
                                 codigo_cupom varchar(255) not null,
                                 tipo_desconto varchar(255) not null check (tipo_desconto in ('PERCENTUAL','FIXO')),
                                 primary key (id)
);

create table tb_pedido_status_historico (
                                            id bigint generated by default as identity,
                                            momento timestamp(6) with time zone,
                                            pedido_id bigint,
                                            status_anterior varchar(255) check (status_anterior in ('RASCUNHO','AGUARDANDO_PAGAMENTO','PAGAMENTO_CONFIRMADO','EM_PRODUCAO','EM_SEPARACAO','AGUARDANDO_ENVIO','ENVIADO','ENTREGUE','CANCELADO','REEMBOLSADO')),
                                            status_novo varchar(255) check (status_novo in ('RASCUNHO','AGUARDANDO_PAGAMENTO','PAGAMENTO_CONFIRMADO','EM_PRODUCAO','EM_SEPARACAO','AGUARDANDO_ENVIO','ENVIADO','ENTREGUE','CANCELADO','REEMBOLSADO')),
                                            primary key (id)
);

create table tb_perfil (
                           id bigint generated by default as identity,
                           nome varchar(50) not null unique,
                           primary key (id)
);

create table tb_perfil_usuario (
                                   perfil_id bigint not null,
                                   usuario_id bigint not null
);

create table tb_produto (
                            altura integer,
                            ativo boolean not null,
                            comprimento integer,
                            custo_producao numeric(15,4) not null,
                            data_prevista_lancamento date,
                            estoque_minimo integer not null,
                            largura integer,
                            peso float(53),
                            preco_revenda numeric(15,2) not null,
                            preco_varejo numeric(15,2) not null,
                            quantidade_estoque integer not null,
                            categoria_id bigint not null,
                            data_atualizacao timestamp(6) with time zone,
                            data_cadastro timestamp(6) with time zone not null,
                            id bigint generated by default as identity,
                            sku varchar(100) not null unique,
                            nome varchar(150) not null,
                            descricao TEXT,
                            img_url varchar(255),
                            tipo_estoque varchar(255) not null check (tipo_estoque in ('ESTOQUE','SOB_DEMANDA','PRE_VENDA')),
                            primary key (id)
);

create table tb_usuario (
                            ativo boolean not null,
                            data_criacao timestamp(6) with time zone not null,
                            id bigint generated by default as identity,
                            username varchar(30) not null unique,
                            password varchar(255) not null,
                            primary key (id)
);

alter table if exists tb_cliente
    add constraint FK4x99w8pcrk3btisu4aw1t0ryl
        foreign key (usuario_id)
            references tb_usuario;

alter table if exists tb_endereco
    add constraint FKtqe8u5ggrtf93dr80hiibdfd
        foreign key (cliente_id)
            references tb_cliente;

alter table if exists tb_item_pedido
    add constraint FK3qvnhpdyxagngbf1t326cvnse
        foreign key (pedido_id)
            references tb_pedido;

alter table if exists tb_item_pedido
    add constraint FKgfmv77km3wt2evaaq2vkiv2oj
        foreign key (produto_id)
            references tb_produto;

alter table if exists tb_opcao_frete_pedido
    add constraint FKrknwj58q1ropggcfna9okoxhx
        foreign key (pedido_id)
            references tb_pedido;

alter table if exists tb_pedido
    add constraint FKajo6v90obpung9h40lcain479
        foreign key (cliente_id)
            references tb_cliente;

alter table if exists tb_pedido
    add constraint FKhbux1bhtr20q091e51dc98dkc
        foreign key (pagamento_id)
            references tb_pagamento;

alter table if exists tb_pedido_cupom
    add constraint FK5ug7vq7d77vwjtod33ekq68rl
        foreign key (cupom_id)
            references tb_cupom_desconto;

alter table if exists tb_pedido_cupom
    add constraint FKfve8if38ok9hst7fne9rghhlu
        foreign key (pedido_id)
            references tb_pedido;

alter table if exists tb_perfil_usuario
    add constraint FK2k6xaedffubppueu4je807r7v
        foreign key (perfil_id)
            references tb_perfil;

alter table if exists tb_perfil_usuario
    add constraint FKqeu7y7fuxn54gtaoyfptdog1q
        foreign key (usuario_id)
            references tb_usuario;

alter table if exists tb_produto
    add constraint FK1ksfe2oumgjxke3oc5op41lej
        foreign key (categoria_id)
            references tb_categoria;
